// Generated by CoffeeScript 1.8.0
(function() {
  var net, port, server;

  net = require('net');

  port = 3030;

  server = net.createServer(function(client) {
    console.log("server connected from " + client.remoteAddress + "!");
    client.on('data', function(data) {
      return console.log("client sent: " + (data.toString()));
    });
    return client.on('end', function() {
      return console.log('server disconnected!');
    });
  });

  server.listen(port);

  console.log("listening on port " + port);

}).call(this);
